=== D-iii-S/everbeen/bpk-conventions/src/main/resources/cz/cuni/mff/d3s/been/bpk/bpk-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        targetNamespace="http://been.d3s.mff.cuni.cz/bpk/config"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:bpk="http://been.d3s.mff.cuni.cz/bpk/config">

    <xsd:element name="bpkConfiguration">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="bpk:metaInf" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="bpk:runtime" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="metaInf">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="groupId" type="xsd:string"/>
                <xsd:element name="bpkId" type="xsd:string"/>
                <xsd:element name="version" type="xsd:string"/>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <!-- Collections -->
    <xsd:element name="bpkArtifacts">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="artifact" type="bpk:ArtifactIdentifier" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="bpkDependencies">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="dependency" type="bpk:BpkIdentifier" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- Data holders -->
    <xsd:complexType name="BpkIdentifier">
        <xsd:sequence>
            <xsd:element name="groupId" type="xsd:string"/>
            <xsd:element name="bpkId" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ArtifactIdentifier">
        <xsd:sequence>
            <xsd:element name="groupId" type="xsd:string"/>
            <xsd:element name="artifactId" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Possible package types -->
    <xsd:complexType name="BpkRuntime">
        <xsd:sequence>
            <xsd:element ref="bpk:bpkDependencies" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="JavaRuntime">
        <xsd:complexContent>
            <xsd:extension base="bpk:BpkRuntime">
                <xsd:sequence>
                    <xsd:element ref="bpk:bpkArtifacts" minOccurs="0"/>
                    <xsd:element name="jarFile" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="runtime" type="bpk:BpkRuntime"/>

    <xsd:element name="java" type="bpk:JavaRuntime"/>

    <xsd:complexType name="NativeRuntime">
        <xsd:complexContent>
            <xsd:extension base="bpk:BpkRuntime">
                <xsd:sequence>
                    <xsd:element name="binary" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="native" type="bpk:NativeRuntime"/>

    <!--

        BEEN is not prepared to use modules.

        <xsd:complexType name="Module">
            <xsd:complexContent>
                <xsd:extension base="bpk:BpkRuntime">
                    <xsd:sequence>
                        <xsd:element ref="bpk:providedInterfaces" minOccurs="0"/>
                    </xsd:sequence>
                </xsd:extension>
            </xsd:complexContent>
        </xsd:complexType>

        <xsd:element name="module" type="bpk:Module"/>

        <xsd:element name="providedInterfaces">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="interface" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>

    -->

</xsd:schema>

=== D-iii-S/everbeen/bpk-conventions/src/test/resources/cz/cuni/mff/d3s/been/bpk/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<bpkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bpk-config.xsd">
  <metaInf>
    <groupId>groupId</groupId>
    <bpkId>bpkId</bpkId>
    <version>version</version>
  </metaInf>

  <runtime />
  
  <!-- 
  <java xsi:type="BpkRuntime">
    <bpkDependencies/>
    <bpkArtifacts>
    	<artifact>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-compress</artifactId>
    		<version>1.4</version>
    	</artifact>
    </bpkArtifacts>
    <jarFile>myCreepyStupidCrazyArchive.jar</jarFile>
  </java>
   -->
  <bpkDependencies>
    <dependency>
      <groupId>groupId</groupId>
      <bpkId>bpkId</bpkId>
      <version>version</version>
    </dependency>
  </bpkDependencies>
</bpkConfiguration>
